theme: jekyll-theme-midnight
title: Digital Brain
description: Welcome to my (digital) brain! This site is a collection of all things that I think are worth to remember: links, notes, daily logs, etc.
